export const ARAB_COUNTRIES = [
  { code: 'SA', name: 'السعودية' },
  { code: 'AE', name: 'الإمارات' },
  { code: 'KW', name: 'الكويت' },
  { code: 'BH', name: 'البحرين' },
  { code: 'QA', name: 'قطر' },
  { code: 'OM', name: 'عُمان' },
  { code: 'EG', name: 'مصر' },
  { code: 'JO', name: 'الأردن' },
  { code: 'LB', name: 'لبنان' },
  { code: 'SY', name: 'سوريا' },
  { code: 'IQ', name: 'العراق' },
  { code: 'YE', name: 'اليمن' },
  { code: 'PS', name: 'فلسطين' },
  { code: 'SD', name: 'السودان' },
  { code: 'LY', name: 'ليبيا' },
  { code: 'TN', name: 'تونس' },
  { code: 'DZ', name: 'الجزائر' },
  { code: 'MA', name: 'المغرب' },
  { code: 'MR', name: 'موريتانيا' },
  { code: 'SO', name: 'الصومال' },
  { code: 'DJ', name: 'جيبوتي' },
  { code: 'KM', name: 'جزر القمر' }
];
